Glue templates
MoveOnOrg/terraform-aws-controlshift-redshift-sync pull request #16
Opened 2023-11-17 23:24 UTC by ibrand

Glue job templating done such that the glue job pulls the latest signatures_job.py script from csl when we terraform deploy so we don't need to manually update the glue code anymore

2023-11-27 20:39 UTC, sjwmoveon requested changes
This mostly makes sense but I have a couple questions.

2023-11-27 20:39 UTC, sjwmoveon commented on glue_job.tf
> -  configuration = jsonencode(
Why are we getting rid of this bit?

2023-11-27 20:39 UTC, sjwmoveon commented on glue_job.tf
> -  lifecycle_rule {
Seems like we would want to keep this rule for deleting temp files?

2023-11-27 21:13 UTC, ibrand commented
So, this was a direct copypaste from https://github.com/controlshift/terraform-aws-controlshift-redshift-sync/blob/main/glue_job.tf which is why some of those blocks were removed. I think either one or both of those blocks might need to be written differently in the newer terraform format (for example pasting the `lifecycle_rule` block back in throws errors) -- do you think it's worth debugging?

2023-11-27 21:21 UTC, sjwmoveon commented on glue_job.tf
> -  configuration = jsonencode(
https://github.com/MoveOnOrg/terraform-aws-controlshift-redshift-sync/commit/4a2e1c32a1036e892a3e6fb647c2b7d51fd34b9c looks like we manually set this part of the configuration so we may want to keep it.

2023-11-27 21:23 UTC, sjwmoveon commented on glue_job.tf
> -  lifecycle_rule {
Similarly we added this manually added lifecycle rule to the config: https://github.com/MoveOnOrg/terraform-aws-controlshift-redshift-sync/commit/19be449c3420f05b3f590e2baa8611d59472ae67 and https://github.com/MoveOnOrg/terraform-aws-controlshift-redshift-sync/commit/7fa1de1bf76bd0739438572e8cfcea5c1b6b4113

2023-11-27 21:23 UTC, sjwmoveon commented
I think it's worth debugging since both changes were made intentionally on our end to do some extra cleanup.

2023-11-29 19:56 UTC, sjwmoveon commented on glue_job.tf
> -  number_of_workers = 9
This also was set manually

2023-11-29 21:54 UTC, ibrand commented
Oh I see that you added the manual changes back in! Does this mean that you got it to deploy without errors with them?

2023-11-29 21:55 UTC, sjwmoveon commented
I did, yes!  No luck with the results of the Glue job, though.

2023-11-29 21:56 UTC, ibrand commented
I'd say we're good to merge in then!

2023-11-29 21:56 UTC, sjwmoveon approved these changes
Approved with the more recent changes.  @ibrand you may want to take another look as well since I made the last few commits.

2024-01-11 19:13 UTC, sjwmoveon requested changes
I think we want to undo all of this since we're not going with the templated Glue job any more.  Fortunately it was never checked in.

2024-01-11 21:23 UTC, ibrand commented
Great! I didn't realize it was never checked in. Closing this.

2024-01-11 21:23 UTC, closed without merging